Fix broken no_new option execution in helper old_new_per_device (#30)
It is used in not widely known but useful option {diff,patch,deploy} --clear.
Now since 2389034 it results in error:

UnboundLocalError: cannot access local variable 'old_json_fragment_files' where it is not associated with a value.